- ChatTTS/utils/infer_utils.py
发现代码在Mac的MPS框架上运行时，效果很差，这是因为CustomRepetitionPenaltyLogitsProcessorRepeat的处理在MPS上，可能会发生score变量数值错误的未知异常，将其连续化scores.contiguous(), 可以解决此问题。
> Ensuring logits scores are contiguous resolved the bug on MPS，Mac MPS bug修复

- ChatTTS/utils/infer_utils.py
在Mac的MPS框架上运行代码时，发现性能表现不佳。这是由于CustomRepetitionPenaltyLogitsProcessorRepeat处理在MPS上运行时，导致score变量出现数值错误的异常。将scores变量进行连续内存排布处理，即使用scores.contiguous()方法，可以解决这个问题。
> Ensuring logits scores are contiguous resolved the bug on MPS

- ChatTTS/core.py
Windows not yet supported for torch.compile 
报错位置 ChatTTS->core.py->125:      gpt.gpt.forward = torch.compile(gpt.gpt.forward,  backend='inductor', dynamic=True)
```python
if compile and 'cuda' in str(device):
gpt.gpt.forward = torch.compile(gpt.gpt.forward,  backend='inductor', dynamic=True)
```
希望修改为
```python
if compile and 'cuda' in str(device):
try:
gpt.gpt.forward = torch.compile(gpt.gpt.forward, backend='inductor', dynamic=True)
except RuntimeError as e:
logging.warning(f'Compile failed,{e}. fallback to normal mode.')
```
以拦截 平台不支持compile 出现RuntimeError 处理方式继续以普通模式运行并打印log输出原因。
> Windows not yet supported for torch.compile fix

- ChatTTS/core.py
要求最低显存为4G，实际上4GB显存的GPU被检测为4095.75 MB。现已将阈值调整为4095 MB。
使用 https://github.com/2noise/ChatTTS/blob/main/ChatTTS/utils/gpu_utils.py#L5 检测 NVIDIA GeForce GTX 1650 的显存结果
```
WARNING:ChatTTS.utils.gpu utils:GPU 0 has 4095.75 MB memory left.
```
其他显卡例如：GeForce GTX 1050 Ti 的检测结果也是一样。
> [fix] Adjust GPU memory check threshold

- examples/web/funcs.py
- examples/web/webui.py
Disable `torch.compile` by default on Windows as it is not supported on Windows yet and gives an unclear error message about z3: https://github.com/pytorch/pytorch/issues/123022
> Disable torch.compile on Windows for webui demo

- ChatTTS/model/dvae.py
This PR addresses the issue of redundant transposition operations:
1. The original DVAE forward method included a transpose operation:
```python
dec_out = self.out_conv(
self.decoder(
input=vq_feats.transpose_(1, 2), <- here
).transpose_(1, 2),   <- and here
)
```
2. This transpose was then repeated in the DVAEDecoder forward method:
```python
def forward(self, input: torch.Tensor, conditioning=None) -> torch.Tensor:
x = input.transpose_(1, 2) <- again
...
return x.transpose_(1, 2) <-  also extraneous transpose
```
> refactor: remove unnecessary transpositions

- docs/cn/README.md
The README of Chinese has been updated with the latest changes
> doc: sync latest README

- examples/api/README.md
- examples/api/client.py
- examples/api/main.py
- examples/api/requirements.txt
This PR adds an API example using FastAPI. Generated audio files are saved to a zip file which is returned in the response. I was using the `/generate_audio` endpoint included with the Gradio app in a previous version of ChatTTS, but that doesn't seem to be supported any more, so this provides an example for how to use ChatTTS via API without using gradio. I have also included a `client.py` example which shows how to use the API.
Related issues: 
close #491
close #448
> feat(api): add chattts api example using fastapi

- ChatTTS/core.py
1. Request buffer size.
2. Remove padding zeros.
https://github.com/2noise/ChatTTS/issues/521
```
[idx=1] 总耗时: 18.45 递增耗时:0.00 Received: len(message)=16000 Total: 16000
[idx=2] 总耗时: 19.46 递增耗时:1.01 Received: len(message)=16000 Total: 32000
[idx=3] 总耗时: 20.33 递增耗时:0.87 Received: len(message)=16000 Total: 48000
[idx=4] 总耗时: 21.05 递增耗时:0.72 Received: len(message)=16000 Total: 64000
[idx=5] 总耗时: 21.05 递增耗时:0.00 Received: len(message)=14848 Total: 78848
[idx=1] 总耗时: 4.23 递增耗时:0.00 Received: len(message)=78848 Total: 78848
```
> fix stream mode, last chunk of audio file size

- ChatTTS/model/velocity/model_runner.py
Fix vLLM wrapper bug
1 . noise at the beginning of the speech
> Fix vLLM wrapper bug: noise at the beginning of the speech

- ChatTTS/core.py
- ChatTTS/model/tokenizer.py
修复一些问题，并使得zero-shot功能可以在不支持torch.uint16的低版本torch上运行
#631
> 降低zero-shot功能对torch版本的要求

- ChatTTS/core.py
The code is not valid 
```
del_all(logits_warpers)
del_all(logits_processors)
```
for `generate` function is used `yield` as a return. As a result , `generate` has not been finished yet, and the wrapper has beed deleted.
> fix: topK and topP not valid

- ChatTTS/model/speaker.py
To allow tuning for `speaker_embeds` tensor. The PR includes:
1. Rename: `_sample_random -> sample_random_tensor` to allow usage out of class.
2. The `spk_emb` argument in `Speaker.apply()` changes `str -> Union[str, torch.Tensor]`
3. Add `inplace` argument to support gradient backward when setting to `False`
4. Update return type to return `torch.Tensor`
Besides, I don't quite see the advantage and motivation to encode the `speaker_embeds` tensor to string. To me, it only makes things more complex. I would personally prefer cpu `torch.Tensor` or `np.ndarray`
cc @fumiama
> Add finetuning support for `Speaker` class

- ChatTTS/core.py
Otherwise, user scripts cannot enable the experimental feature
> add experimental argument

- ChatTTS/core.py
- ChatTTS/model/dvae.py
- ChatTTS/model/embed.py
This PR addresses RuntimeErrors caused by device mismatches between various components of the model. These errors occur when tensors are on different devices (CPU and CUDA).
Changes made:
1. In `ChatTTS/core.py`:
- Modified `embed.from_pretrained()` call to include the device parameter.
- Explicitly moved the embed model to the specified device.
- Added device parameter to DVAE initialization.
2. In `ChatTTS/model/embed.py`:
- Updated `from_pretrained()` method to accept a device parameter.
- Added a `to(device)` call to ensure the model is on the correct device.
3. In `ChatTTS/model/dvae.py`:
- Added device parameter to `MelSpectrogramFeatures` initialization.
- Ensured audio tensor is moved to the correct device in the forward method.
- Added device parameter to DVAE initialization. …
> Fix device mismatch error in embedding loading on branch dev

- ChatTTS/model/velocity/model_runner.py
The idx should be changed when decode phrase, now it's always the one in prefill phrase.
> fix idx error when do repetition penalty

- ChatTTS/core.py
This PR is a bugfix for Ascend NPU when using ChatTTS to sample the voice of a real speaker.
- OS: ubuntu 20.04
- NPU: Atlas 300T A2
- CANN: 8.0.RC2
- torch-npu: 2.1.0.post6
- torch: 2.1.0
Complex dtype used in the process of computing MelSpectrogram is not supported in `torch_npu` now, and we could get a error when sampling the voice of a real speaker.
The logs are showed below:
```bash
[+0000 20241016 12:19:06] [WARN]  WebUI  | funcs | no ffmpeg installed, use wav file output
[+0000 20241016 12:19:06] [INFO]  WebUI  | webui | loading ChatTTS model...
[+0000 20241016 12:19:06] [INFO] ChatTTS | dl | checking assets...
/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/gradio/analytics.py:106: UserWarning: IMPORTANT: You are using gradio version 4.44.0, however …
```
> Fix for Ascend NPU when using ChatTTS to sample the voice of a real speaker

- README.md
Pinning python version would be really useful for new users trying to struggle through python dependency hell.
> python 3.12 fails to install requirements, 3.13 not supported.

- ChatTTS/core.py
- tools/audio/av.py
Currently, it's the program only allows you to use "huggingface," "local," or "custom" but none allow you to specify a directory where you want to download a file automatically using ```snapshot_download."  This fixes that.
This pull request implements the following:
Here's a brief summary of the different options for handling model files in ChatTTS:
`source="huggingface"`: Downloads models from HuggingFace repo to ~/.cache/huggingface
* or to cache_dir if specified
`source="local"`: Downloads models from HuggingFace repo to current working directory
* or to cache_dir if specified
`source="custom"`:
* No change
```python
from ChatTTS import Chat
chat = Chat()
chat.load(
source="huggingface",
cache_dir="path/to/your/models",
device="cuda"
)
chat = Chat()
chat.load(
source="local", …
> add cache_dir parameter

- examples/api/main.py
Allow empty params_refine_text, and load normalizers to handle chinese numbers
> fix: allow empty params_refine_text, and load normalizers to handle chinese numbers
