2noise/ChatTTS

- README.md
Not sure about the formal part but I think people are looking for demo (https://news.ycombinator.com/item?id=40507039) - working super well btw :)
> README.md: add link to Space demo

- README.md
- README_CN.md
- README_JP.md
I created Japanese translated README.
> docs; add Japanese README

- README.md
correct the grammar in the README.md file.
> Grammar correction for README.md

- ChatTTS/utils/gpu_utils.py
Add support Apple M1/M2 chips with Metal Performance Shaders
> Add apple gpu mps backend

- README.md
Allows user to experience chatTTS in one shot.
> Google Colab Demo

- ChatTTS/core.py
- ChatTTS/model/gpt.py
- requirements.txt
fix #216
fix #215
fix #110
fix #106
fix #60
fix #186
fix #160
fix #101
> fix: normalizer fallback & mps infer

- .github/workflows/checksum.yml
- ChatTTS/core.py
- ChatTTS/utils/download.py
- examples/cmd/run.py
- examples/web/webui.py
- requirements.txt
- sha256.env
- tools/checksum/main.go
- tools/checksum/tmpl.go
rename original `local` to `custom`
> feat(core): add load_models source `local`

- docs/cn/README.md
Translate newest README to Chinese
> doc: translate README

- ChatTTS/model/gpt.py
- examples/ipynb/example.ipynb
- examples/web/webui.py
> fix(examples): ipnyb infer

- examples/ipynb/colab.ipynb
> fix(examples): colab infer

- ChatTTS/core.py
- ChatTTS/model/gpt.py
- ChatTTS/utils/download.py
- ChatTTS/utils/gpu_utils.py
- ChatTTS/utils/infer_utils.py
- ChatTTS/utils/io.py
- ChatTTS/utils/log.py
- examples/cmd/run.py
- examples/web/funcs.py
- examples/web/webui.py
- tools/logger/__init__.py
- tools/logger/log.py
- move log definition out of ChatTTS
- apply colorful log level
- optimize webui logic
- split webui into 2 files for clear reading
> optimize: log & webui

- examples/ipynb/colab.ipynb
- examples/ipynb/example.ipynb
Changes made:
- add example of custom loading method.
- revise the structure of Load Models part.
This refactoring improves the readability of the code and reduces unnecessary clutter. The functionality of the code remains unchanged.
Please review and provide feedback. (๑′ᴗ‵๑)
> refactor: revise the Load Models part of examples/ipynb

- requirements.txt
> fix(req): restrict normalizer' installation to linux

- ChatTTS/model/dvae.py
when use_decoder=False
introduced in #383
maybe related to #400
> fix(dvae): dvae _embed permute mismatch

- ChatTTS/core.py
- ChatTTS/model/dvae.py
- requirements.txt
- setup.py
and unify coef of dvae & decoder
> feat(dvae): expose coef for customize

- ChatTTS/core.py
- ChatTTS/infer/api.py
- ChatTTS/utils/dl.py
- examples/web/funcs.py
> optimize(chat): move gpt&decoders out of dict

- setup.py
#426
Modify as follows:
1. Add the `__init__.py` file to ensure that setup is automatically imported.
```
ChatTTS/
├── experimental/
│   └── ...
├── infer/
│   ├── __init__.py       # 确保这个文件存在
│   ├── model/
│   │   ├── __init__.py   # 确保这个文件存在
│   │   ├── dva.py
│   │   └── gpt.py
│   └── utils/
│       ├── __init__.py   # 确保这个文件存在
│       └── ...
└── ...
```
2. Modify `setup.py` to make sure `homophones_map.json` is imported properly.
> fix(install): incomplete installation

- ChatTTS/model/gpt.py
- ChatTTS/model/processors.py
- examples/web/ex.py
- examples/web/funcs.py
- examples/web/webui.py
and fix wenui infer without refine text
> optimize(model): more torch funcalls

- .github/workflows/unitest.yml
- ChatTTS/core.py
- ChatTTS/model/gpt.py
- examples/ipynb/colab.ipynb
- examples/ipynb/example.ipynb
- examples/web/funcs.py
- examples/web/webui.py
> optimize: spk_emb & generate & webui

- README.md
I encountered the bug described at [issue](https://github.com/2noise/ChatTTS/issues/561) and solved it by adding unsqueezing before saving it.
> Update reademe.md to fix save audio bug in the demo

- ChatTTS/model/velocity/model_runner.py
> chore: optimize tensor padding in model_runner.py
